Add .travis.yml

diff --git a/alpine-chroot-install b/alpine-chroot-install
--- a/alpine-chroot-install
+++ b/alpine-chroot-install
@@ -77,13 +77,13 @@ set -eu
 APK_TOOLS_URI='http://fr.alpinelinux.org/alpine/v3.4/main/x86_64/apk-tools-static-2.6.7-r0.apk'
 APK_TOOLS_SHA256='342458308b8ebdb6a91d347b6b2cced7349c0cd0560a7fd7cdd71c5e1aa2b9f3'
 APK_KEYS_URI='http://alpinelinux.org/keys'
-# TODO: Add key 58199dcc.
 APK_KEYS_SHA256="\
 	9c102bcc376af1498d549b77bdbfa815ae86faa1d2d82f040e616b18ef2df2d4  alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
 	2adcf7ce224f476330b5360ca5edb92fd0bf91c92d83292ed028d7c4e26333ab  alpine-devel@lists.alpinelinux.org-4d07755e.rsa.pub
 	ebf31683b56410ecc4c00acd9f6e2839e237a3b62b5ae7ef686705c7ba0396a9  alpine-devel@lists.alpinelinux.org-5243ef4b.rsa.pub
 	1bb2a846c0ea4ca9d0e7862f970863857fc33c32f5506098c636a62a726a847b  alpine-devel@lists.alpinelinux.org-524d27bb.rsa.pub
-	12f899e55a7691225603d6fb3324940fc51cd7f133e7ead788663c2b7eecb00c  alpine-devel@lists.alpinelinux.org-5261cecb.rsa.pub"
+	12f899e55a7691225603d6fb3324940fc51cd7f133e7ead788663c2b7eecb00c  alpine-devel@lists.alpinelinux.org-5261cecb.rsa.pub
+	73867d92083f2f8ab899a26ccda7ef63dfaa0032a938620eda605558958a8041  alpine-devel@lists.alpinelinux.org-58199dcc.rsa.pub"
 VERSION='0.0.0'
 
 
@@ -180,7 +180,7 @@ while getopts 'a:b:d:i:m:p:r:t:hv' OPTION; do
 done
 
 if [ "$(id -u)" -ne 0 ]; then
-	die 'This script must be run as root'
+	die 'This script must be run as root!'
 fi
 
 
@@ -194,7 +194,7 @@ einfo 'Downloading APK keys'
 
 echo "$APK_KEYS_SHA256" | while read sha256 keyname; do
 	wgets "$APK_KEYS_URI/$keyname" $sha256 "$CHROOT_DIR"/etc/apk/keys \
-		|| die 'Failed to download or verify APK key'
+		|| die 'Failed to download or verify APK key!'
 done
 
 
